### ISSUE TITLE
Winnie the Pooh in the Hundred Acre Wood

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#193]
According to https://www.scummvm.org/compatibility/DEV/winnie/ ScummVM should support Apple II\Commodore 64\Amiga versions, however I couldnt get it to detect any of these.

**Comment by exoscoriae** [comment]
added apple 2, amiga, and c64 versions. rebuilt menus. repacked\renamed folders & game.

c64 version has some odd color issues, but that is currently just how scummvm emulates it. We can disable that one if you want.
