### ISSUE TITLE
Zork - Grand Inquisitor (CD Windows)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#195]
Its recommended (https://wiki.scummvm.org/index.php?title=Zork:_Grand_Inquisitor) to install this patch: 
[Zork_Grand_Inquisitor_Patch_12.zip](https://github.com/exoscoriae/eXoScummVM/files/6130296/Zork_Grand_Inquisitor_Patch_12.zip)

However the files are packed and need to be run on an installed copy of the game. I do not currently have the setup to do so.

**Comment by exoscoriae** [comment]
patched and re-upped
