### ISSUE TITLE
Clandestiny (CD Windows)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#242]
Little more than walking around the rooms is currently possible in ScummVM. Also ScummVM says there are CD tracks that need to be extracted from the original disks but I didnt find any copies that werent ISO format.

Added to the Missing Games project in relation to the need of the full CD with CD Tracks

The game has issues with stable 2.5 ScummVM build (says the GroovieV2 engine is not compiled in), and will only work using the 2.3_18903 svn build

**Comment by exoscoriae** [comment]
Added to 2.6. Moved to working
