### ISSUE TITLE
Pink Panther, The - Passport to Peril (CD Windows)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#255]
Has warning message that the game isnt fully supported yet. Nothing we can do on our end.

also

The game has issues with stable 2.5 ScummVM build, and will only work using the 2.3_18903 svn build

**Comment by exoscoriae** [comment]
went into official testing with 2.7. Added to svn 2.7 build

**Comment by Python-Exoproject** [comment]
Now in official 2.7
