### ISSUE TITLE
Cruise for a Corpse (Atari ST)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#28]
While the intro is English, the actual game text is German. This is true even in the Atari ST emulator STEEM for the version I found (https://www.myabandonware.com/game/cruise-for-a-corpse-1mv#Atari%20ST)

Also sound is not currently supported by ScummVM. Could probably force it through SB instead of Atari ST sound but then wouldnt be Atari.

**Comment by exoscoriae** [comment]
confirmed in other dumps as well.

forcing sound would not be recommended.

**Comment by Python-Exoproject** [comment]
Found other games with similar issue, Fascination (Atari ST) #282, and Bargon Attack (Atari ST) #22

**Comment by Python-Exoproject** [comment]
Same in 2.6.1

**Comment by Python-Exoproject** [comment]
Copy found by Smiling Spectre that was English throughout
