### ISSUE TITLE
Eye of the Beholder (PC-98)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#281]
When ScummVM prompts you and you select to import a detected save it crashes to a console error.

**Comment by exoscoriae** [comment]
works fine when not using command line. seems to be an issue with launching from the command line?

**Comment by Python-Exoproject** [comment]
Thanks, that was the clue I needed. The issue was that by running via command line with gameid 'eob' it was using the same savegame storage that the other platforms use. While the other platforms can interchange savegames, the PC-98 cant. By giving it its own gameid setup in our exoscummvm scummvm.ini it separated it from the others and now works
