### ISSUE TITLE
7th Guest, The

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#295]
DOS, Mac and iOS versions

**manual**
Official DOS manual included

**extras**
- Guide
- Novel
- Reference Card (DOS, C64, Amiga, Atari, Apple)
- The Stauf Files

**Comment by TimberlAndRE-de** [comment]
found 

- [x] mac cd-booklet as extra manual

added to the github folder


iOS version has no manual

**Comment by exoscoriae** [comment]
added
