### ISSUE TITLE
Backyard Baseball

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#303]
Windows manual missing

**Comment by SmilingSpectre** [comment]
https://oldgamesdownload.com/wp-content/uploads/Backyard_Baseball_1997_Manual_Win_EN.pdf

**Comment by TimberlAndRE-de** [comment]
thx @SmilingSpectre 

- [ ] WIN and MAC manual

added to the github folder

**Comment by exoscoriae** [comment]
added
