### ISSUE TITLE
Beyond Zork - The Coconut of Quendor

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#319]
**manual**
DOS manual is needed

**extras**
- InvisiClues Map
- The Lore of Legends of Quendor
- Hintbook
- Cluebook (txt)
- Map

**Comment by TimberlAndRE-de** [comment]
found
- [x] DOS manual
- [x] quick start guide

added to the github folder

**Comment by exoscoriae** [comment]
added manual and quickstart guide
