### ISSUE TITLE
Elvira 1 - Mistress of the Dark (Atari ST)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#32]
Our copy has an initial screen that possibly implies its a Demo version?

Also ScummVM does not currently support music in the Atari ST version.

**Comment by exoscoriae** [comment]
unable to find any other copies that do not have that screen. 

the file size is the same as the amiga version. so I doubt it is a demo.

**Comment by Python-Exoproject** [comment]
Ok, closing the issue and creating one for just the sound issue
