### ISSUE TITLE
Black Cauldron, The

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#324]
DOS, Apple II and Amiga game versions 
current manual has no sign of platform dependencies

Extras included:
- hint book
- VGmap
- reference card (PC)

**Comment by TimberlAndRE-de** [comment]
found

- [x] reference card (Amiga)
- [x] reference card (Apple II)

added to the github folder

**Comment by exoscoriae** [comment]
added to extras
