### ISSUE TITLE
Eye of the Beholder (PC-98)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#33]
Only partially in English, may need to go with other foreign language games.

**Comment by exoscoriae** [comment]
none of the pc-98 games are going to be fully in english, afaik.

PC-98 inherently implies it will be Japanese.

**Comment by Python-Exoproject** [comment]
Some are completely English, but not many. Ive decided to just add a user note to the game launch bat informing of Japanese interface.
