### ISSUE TITLE
Eye of the Beholder

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#34]
All versions come with a save file default party. ScummVM asks to import it on every load though, so need to add system to only do this once.

**Comment by exoscoriae** [comment]
I looked into this, and unless I am misunderstanding, this is standard scummvm behavior. Essentially, each time on load it sees the sav file and asks if you want to use it. What is wrong with the user just clicking "no" after the initial run?

Are you suggesting you want our script to remove the sav file after the initial startup so this question is not asked on subsequent start-ups?

**Comment by Python-Exoproject** [comment]
This screen implies it should happen once, not every launch:

![image](https://user-images.githubusercontent.com/67406191/117969352-a456f680-b36a-11eb-869d-ae61fd8049f4.png)

And everytime you say yes it fills another save slot in the load screen. My suggestion is to delete the imported save after the first launch for each platform like this:

:amiga
.\util\setconsole.exe /minimize
".\scmvm\scummvm.exe" --no-console -F -g3x --platform=amiga --opl-driver=nuked --output-rate=44100 --aspect-ratio -p".\eXoScummVM\%GameDir%\Eye of the Beholder (Amiga)" eob
del ".\eXoScummVM\%GameDir%\Eye of the Beholder (Amiga)\eobdata.sav"
goto end

Then it would be accessible for someone wanting to import into scummvm the default quick start party the first launch but never annoy or fill up save slots after that.

**Comment by Python-Exoproject** [comment]
I figured out what it is, when you run it from inside scummvm it uses the scummvm.ini which sets the line "importOrigSaves=false" once you have run the game the first time. That is what gets it to bypass the question on subsequent runs. As we are using the command line that is not a valid option so we can either do my above suggestion which accomplishes the same end or add all the EOB variants to our internal scummvm.ini

Your preference?

**Comment by Python-Exoproject** [comment]
Games now setup so that scummvm adds the above flag into the eob ini section (needed the section in ini created before scummvm would save the value) after the user has run the game for the first time. The user only gets the opportunity the first time they load the game, after that the flag is set and they will no longer be presented the choice.
