### ISSUE TITLE
Eye of the Beholder II - The Legend of Darkmoon

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#36]
Get save transfer working. 

Also the same issue as Eye of the Beholder I regarding always being asked about the transfer on start

**Comment by exoscoriae** [comment]
same comment as EOB 1. Are you suggesting you want our launch files to remove that save after the initial start-up?

**Comment by Python-Exoproject** [comment]
see EOB 1 (#34) for update on always being asked about importing the quick start party.

As for the transferring of saves from EOB 1, this screen implies there should be no issue with setting it up:

![image](https://user-images.githubusercontent.com/67406191/117973859-3c0b1380-b370-11eb-8955-d71ac1215ac8.png)

but despite all my saves being in the default scummvm savegame folder I get the above. Thoughts?

**Comment by Python-Exoproject** [comment]
Solved as per #34, creating new issue for save transfer problem
