### ISSUE TITLE
Darby the Dragon

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#364]
Win and Mac manuals are missing

**Comment by SmilingSpectre** [comment]
https://www.old-games.ru/game/download/get.php?fileid=19055&modal=1

**Comment by TimberlAndRE-de** [comment]
thx Smiling Spectre

- [ ] WIN and MAC multiplatform manual found

added to the github folder

**Comment by exoscoriae** [comment]
added
