### ISSUE TITLE
Day Of The Tentacle

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#365]
**manual**
official manual included, not platform specific but probably from the CD-Rom release for DOS

**extras**
- Hintbook
- Reference Card (DOS)  _(maybe someone finds the MAC reference card too?)_
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] mac manual (booklet) as an extra

added to the github folder

**Comment by exoscoriae** [comment]
added mac manual
