### ISSUE TITLE
Deadline

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#366]
DOS manual is missing

** extras **
- Cluebook
- Investigative Techniques
- InvisiClues Map
- Dysan Sticker
- Interviews
- Letter
- Memo
- Photo
- Report
- Pills
- Corpus Delicti

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual for PC / DOS

added to the github folder

**Comment by exoscoriae** [comment]
added
