### ISSUE TITLE
Dirty Split

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#370]
Windows manual is missing

**Comment by SmilingSpectre** [comment]
Freeware, accessible from here: https://dreamagination.itch.io/dirty-split

If there is no manual in this set, possibly it's not exists.

**Comment by TimberlAndRE-de** [comment]
nice, thx @SmilingSpectre 

- [ ] WIN manual
- [ ] Soundtrack (mp3)

added to the github folder

**Comment by exoscoriae** [comment]
added manual. debating how to handle the OST

**Comment by TimberlAndRE-de** [comment]
I'm not a fan of adding every single track as an additional application ... the menu list would be very long
maybe the OST could be just added as a folder of mp3s?
or as a zip file so the users can decide themselfs?
would be a pity to just leave it out I think

**Comment by exoscoriae** [comment]
While I agree it is a pity, there really is no reason to add a soundtrack for one game but not the others. That isn't very consistent. The second issue is there is no proper way to present this material. Simply putting it in with the rest of the files doesn't do much good for the majority of users who never go diving into the file structure and just access everything through the front end anyways.

So, for these reasons, the soundtrack will be declined. I will however take the title track and add it to the music folder
