### ISSUE TITLE
Dragon History

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#374]
DOS manual is missing

**Comment by Eulisker** [comment]
This was a czech game and only ever released there. See [here](https://www.ucw.cz/draci-historie/index-en.html)

I can not find the czech manual.

**Comment by TimberlAndRE-de** [comment]
Thx for the hint
I found there is no Czech manual, only Czech readme
Since the same readme is included with the Czech, Polish and English version I guess there is no translation for it yet
Added to the GitHub folder

**Comment by exoscoriae** [comment]
added
