### ISSUE TITLE
Elvira 2 - The Jaws of Cerberus

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#382]
**manuals**
Amiga and DOS manual (multi-platform) already included
Atari ST manual is missing

**extras**
- interactive code wheel
- Hintbook

**Comment by TimberlAndRE-de** [comment]
there is no Atari ST Manual, it had the same manual for Amiga and DOS included
but there is a

- [ ] Reference Card (Atari ST)

added to the github folder

**Comment by exoscoriae** [comment]
added reference card
