### ISSUE TITLE
Eye of the Beholder II - The Legend of Darkmoon

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#386]
**manual**
multi-platform manual (rule book) already included (PC, Amiga, FM-Towns)

**extras**
- Cluebook
- Quick Reference Card (PC)
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Reference Card (Amiga)
- [ ] Manual (FM-Towns) (not sure if the japanese stuff is wanted ;) ... )

as extras
added to the github folder

**Comment by exoscoriae** [comment]
added
