### ISSUE TITLE
Flight of the Amazon Queen

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#392]
**manual**
DOS manual included,
Amiga manual is missing

**extras**
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] non-platform manual (maybe set as manual and set current DOS manual as extra?) also for Amiga
- [ ] Playing Guide
- [ ] Reference-Card Amiga

added to the github folder

**Comment by exoscoriae** [comment]
added/switched manual
