### ISSUE TITLE
Future Wars

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#405]
**manual**
multi-platform Amiga / Atari ST manual included
DOS ist missing

**extras**
- Alternate Amiga / Atari ST manual
- Copy Protection sheet
- Quick Reference Card (DOS)

**Comment by TimberlAndRE-de** [comment]
found

- [ ] DOS manual booklet as an extra

added to the github folder

**Comment by exoscoriae** [comment]
added
