### ISSUE TITLE
Gobliiins 1

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#411]
**manual**
Amiga,Atari & DOS multi-platform manual included
MAC is missing

**extras**
- Installguide (DOS)
- Troubleshooting Guide (DOS)
- Hint Book

**Comment by TimberlAndRE-de** [comment]
found

- [ ] code sheet as extra

added to github folder, eXo please put it back in "to do" for the MAC manual

**Comment by exoscoriae** [comment]
added
