### ISSUE TITLE
Gregory and the Hot Air Balloon

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#415]
WIN and MAC manuals are missing

**Comment by SmilingSpectre** [comment]
https://www.old-games.ru/game/download/get.php?fileid=19001&modal=1

**Comment by TimberlAndRE-de** [comment]
thx Smiling Spectre

- [ ] WIn and MAC manual found

added to the github folder

**Comment by exoscoriae** [comment]
added
