### ISSUE TITLE
Hyperspace Delivery Boy

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#442]
WIN manual is missing

**Comment by SmilingSpectre** [comment]
Doc? https://www.oldhandhelds.com/Pocket%20Pc%20Software/Games/Hyperspace%20Delivery%20Boy/HDB%20Manual.doc

**Comment by TimberlAndRE-de** [comment]
thx @SmilingSpectre 

- [ ] WIN manual

added to the github folder

**Comment by exoscoriae** [comment]
added
