### ISSUE TITLE
Indiana Jones and the Fate of Atlantis

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#447]
**manual**
non-platform manual included (for DOS, Mac, Amiga, FM-Towns)

**extras**
- Comic issue 1
- Hint Book
- Quick Reference Card (DOS)
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] reference manual for Amiga
- [ ] reference card for MAC

added to the github folder

**Comment by exoscoriae** [comment]
added
