### ISSUE TITLE
Indiana Jones and the Last Crusade

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#448]
**manual**
IBM manual included
Amiga, Atari, Mac and FM-Towns manuals are missing

**extras**
- Hint book
- Transtaltion Table
- Grail Diary

**Comment by TimberlAndRE-de** [comment]
found

- [ ] alternate Manual without platform specific infos for Amiga, Atari, Mac (FM-Towns has a chinese manual thats still missing)
- [ ] Reference Card (Atari ST)
- [ ] Reference Card (Amiga)
- [ ] Registration Card
- [ ] Order Card

added to the github folder, eXo please put it back in "to do" for the FM-Towns manual

**Comment by exoscoriae** [comment]
added
