### ISSUE TITLE
Inherit the Earth - Quest for the Orb

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#450]
**manual**
IBM/DOS manual included
MAC and PC-98 manuals are missing

**extras**
- Cluebook

**Comment by TimberlAndRE-de** [comment]
found

- [ ] reference card (DOS)

(not sure if the japanese stuff is wanted, so it's on eXo to decide if the following is useful):
- [ ] manual (PC-98)
- [ ] registration cards (PC-98)

added to the github folder, eXo please set back to "to do" for the mac manual

**Comment by exoscoriae** [comment]
added
