### ISSUE TITLE
Journeyman Project, The - Pegasus Prime

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#457]
**manual**
MAC manual is missing

**extras**
- Hints Configuration
- Hints Gameplay
- Technical Leaflet 1
- Technical Leaflet 2

**Comment by TimberlAndRE-de** [comment]
found

- [ ] multiplatform manual for MAC, Linux, Windows

added to the github folder

**Comment by exoscoriae** [comment]
added
