### ISSUE TITLE
King's Quest 1 - Quest for the Crown

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#459]
**manual**
non-platform manual already included (for DOS,WIN,MAC,AppleII,Amiga,Atari ST)

**extras**
- AGDI Game manual (WIN, MAC)
- AGI Hint Book
- Hint Map
- KQ 1-6 Companion
- Keyboard overlay
- The Official Book of Kings Quest
- VGMap
- VGMap (for the remake)

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Reference Card (apple)
- [ ] Technical Reference Manual (Amiga, Atari ST, PC)

added to the github folder

**Comment by exoscoriae** [comment]
added
