### ISSUE TITLE
King's Quest 2 - Romancing the Throne

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#460]
**manual**
non-platform manual already included (for DOS,WIN,MAC,AppleII,Amiga,AtariST)

**extras**
- AGDI Game manual (WIN/DOS)
- Hint Book
- King's Quest 1-6 Companion
- The Official Book of Kings Quest
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] reference card (Atari ST)
- [ ] reference card (Apple II)

added to the github folder

**Comment by exoscoriae** [comment]
added
