### ISSUE TITLE
King's Quest 3 - To Heir is Human

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#461]
**manual**
platform independet manual included (for DOS, WIN, MAC, Apple, Amiga, Atari)

**extras**
- AGDI Game manual (DOS, WIN)
- IA Game Manual (WIN)
- Copy Protection sheet
- Hint Book
- King's Quest 1-6 Companion
- The Official Book of King's Quest
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] reference card (Apple II)

added to the github folder

**Comment by exoscoriae** [comment]
added
