### ISSUE TITLE
King's Quest 4 - The Perils of Rosella

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#462]
**manual**
platform independent manual already included (for DOS, WIN, Apple, Amiga, Atari)

**extras**
- Hint Book
- King's Quest 1-6 Companion
- Answers
- The Official Book of King's Quest 
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] reference card (Apple II)
- [ ] reference card (Atari ST)

added to the github folder

**Comment by exoscoriae** [comment]
added
