### ISSUE TITLE
King's Quest 5 - Absence Makes the Heart Go Yonder

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#463]
**manual**
multi-platform manual included (DOS, Atari ST, Amiga, MAC)
FM-Towns / PC-98 manuals are missing

**extras**
- Hint Book
- KQ 1-6 Companion
- Code table
- Alternate manual (DOS/WIN)
- Alternate manual (DOS, Atari ST, Amiga, MAC)
- Reference Card (DOS)
- The Official Book of King's Quest
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Manual (with Amiga Loading infos)
- [ ] Disk-Exchange order form
- [ ] registration card

(not sure if japanese stuff for the PC-98 is wanted though the included version is english, the following could be added, otherwise just delete it ;-) )
- [ ] PC-98 manual
- [ ] PC-98 Sierra manual
- [ ] PC-98 Addendum
- [ ] PC-98 note
- [ ] PC-98 advert

added to the github folder

**Comment by exoscoriae** [comment]
added
