### ISSUE TITLE
Laura Bow 1 - The Colonels Bequest

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#471]
**manual**
multi-platform manual (DOS, Atari, Amiga) already included

**extras**
- Design Documents
- Fingerprints
- Hint Book
- Map
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Poster for magnifier glass
- [ ] magnifier glass
- [ ] notebook
- [ ] pencil

added to the github folder


proof pic:
![grafik](https://user-images.githubusercontent.com/67441153/120765280-55d7ea80-c519-11eb-8642-10a5983e2bef.png)

**Comment by exoscoriae** [comment]
added
