### ISSUE TITLE
Legend of Kyrandia, The

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#477]
**manual**
DOS manual already included
Amiga and MAC manuals are missing

**extras**
- Official Guide
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual (upgrade, higher resolution from mocagh)
- [ ] MAC manual as extra
- [ ] Reference Card (Amiga)
- [ ] Registration card
- [ ] Westwood Studios News & Notes
- [ ] Addendum
- [ ] Virgin Clothes order card
- [ ] Poster
- [ ] Hint Book

added to the github folder

**Comment by exoscoriae** [comment]
added. replaced manual
