### ISSUE TITLE
Leisure Suit Larry 2 - Goes looking for Love

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#478]
**manual**
platform independent manual already included (for DOS, WIN, Amiga, Atari)

**extras**
- LSL 1-3 Official Guide Book
- Hint Book
- Phone Numbers
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] warranty registration card

added to the github folder

**Comment by exoscoriae** [comment]
added
