### ISSUE TITLE
Inherit the Earth - Quest for the Orb (Macintosh)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#48]
(not the modern release by Wyrmbyte, but the original by The Dreamers Guild)

This should work, however ScummVM keeps reporting that my extracted files are not a recognised version of the game. Either the copies ive found of the game are not exact dumps or the extraction is not working for some reason. Online information says all files should be extracted as Mac Binary 2 which I have done. One person using Linux reported success here: https://forums.scummvm.org/viewtopic.php?t=5976 For now I have disabled the option from the games launch menu.

**Comment by exoscoriae** [comment]
added MAC and Japanese PC-98 versions
