### ISSUE TITLE
Leisure Suit Larry 5 - Passionate Patty Does a Little Undercover Work

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#480]
**manual**
non-platform manual already included (DOS, MAC, Amiga)

**extras**
- Larry 1-6 Official Book
- AeroDork Airlines Pamphlet
- Hint Book
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] LSL 1 flyer advert (from mocagh)

added to the github folder

**Comment by exoscoriae** [comment]
added
