### ISSUE TITLE
King's Quest 1 - Quest for the Crown (Tandy\PCJR)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#49]
According to https://www.scummvm.org/compatibility/DEV/kq1/ Tandy Color Computer 3 is supported but I couldnt successfully extract the files from an image of the 1984 KQ1 version.

**Comment by exoscoriae** [comment]
@Python-Exoproject 
Recognized as CoCo3 by ScummVM. It is possible to detect and run this from the base "King's Quest 1 - Quest for the Crown (Floppy DOS)" folder, by opening scummvm, pointing to it, and adding game. CoCo 3 will come up as an option. There is no sound in this version.

[kq1-coco3.zip](https://github.com/exoscoriae/eXoScummVM/files/6422490/kq1-coco3.zip)
[kq1-coco3-1.zip](https://github.com/exoscoriae/eXoScummVM/files/6422491/kq1-coco3-1.zip)

Attached are specific dumps of the CoCo3 files.  the -1 file has no sound and behaves exactly as if you try to run the CoCo detected files from our existing folder.

The "updated" file refuses to even start.

**Comment by Python-Exoproject** [comment]
Ah, I thought it was similar to the PCJR 1984 version we have in exodos. This version doesnt really look any different that the DOS version so Im not overly concerned about adding it. Your thoughts?

Whatever we decide here probably carries through to all the other Sierra games I've marked for the same reason.

**Comment by exoscoriae** [comment]
Considering they have no sound and the graphics are pretty much identical to the tandy, I am not loosing any sleep over this platform.

**Comment by Python-Exoproject** [comment]
Ill close this and all similar tickets then
