### ISSUE TITLE
Living Books - Just Grandma and Me

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#498]
WIN manual is missing

**Comment by bigjim161** [comment]
Found 2 manuals
one in ENG for mac windows 95 win 3.1
another in ENG FR DE mac windows 95 win 3.1
added to the github folder

**Comment by TimberlAndRE-de** [comment]
thx @bigjim161 
I chosed the 

- [ ] english win manual

added to the github folder

**Comment by exoscoriae** [comment]
added
