### ISSUE TITLE
Journeyman Project, The - Pegasus Prime (CD Windows)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#50]
According to https://www.scummvm.org/compatibility/DEV/pegasus/ this should work but I havent succeeded in getting it to run using the GOG version.

**Comment by exoscoriae** [comment]
Only the windows demo is supported currently. So that page is misleading.

**Comment by Python-Exoproject** [comment]
It seems the only PC version of Pegasus Prime was the DVD version and it is now added to the pack
