### ISSUE TITLE
Loom

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#508]
**manual**
platform independent manual included (for DOS, Amiga, Atari)
FM-Towns and TG-16 manuals are missing

**extras**
- Claves
- Hint Book
- Quick Reference Card (IBM/Tandy)
- Book of Patterns
- Roland Upgrade order card
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Reference Card (Atari ST)
- [ ] Reference Card (Amiga)
- [ ] Cassette (Audio MP3)
- [ ] Cassette images
- [ ] image of the protection code viewer

added to the github folder

**Comment by exoscoriae** [comment]
added
