### ISSUE TITLE
Manhole, The - Enhanced

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#523]
**manual**
WIN cd manual already included

**extras**
- Reference card (DOS)

**Comment by TimberlAndRE-de** [comment]
the included reference card is for DOS
The included version is windows only ...  @exoscoriae please delete the reference card
(I added it to the issuer for the "Manhole, The (Floppy DOS)" version #524  )

**Comment by exoscoriae** [comment]
done
