### ISSUE TITLE
Manhunter 2 - San Francisco

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#526]
**manual**
manual included, it contains some DOS instructions but is also used for all other versions

**extras**
- Quick reference card (DOS, Amiga, Atari ST, Mac, Apple II)
- Hint Book
- ID Card
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Quick reference card (DOS, Amiga, Atari ST, Mac, Apple II) - correct version, current on is for Manhunt - New York
- [ ] Reference Card (Amiga)
- [ ] Sierra 10th anniversary catalog
- [ ] Registration Card

added to the github folder

**Comment by exoscoriae** [comment]
done
