### ISSUE TITLE
Maniac Mansion

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#527]
**manual**
Amiga, Atari, DOS manual already included
NES, Apple, C64 are missing
No WIN manual exists afaik

**extras**
- Hint Book
- Codebook
- Bulletin Board
- Quick Reference Card (IBM PC)

**Comment by TimberlAndRE-de** [comment]
found

- [ ] C64 / Apple II manual
- [ ] NES manual
- [ ] Lucasfilm order card
- [ ] Game-Design-Notes
- [ ] Game-Design-Document

added to the github folder

**Comment by exoscoriae** [comment]
added
