### ISSUE TITLE
Mind Forever Voyaging, A

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#533]
**manual**
DOS manual is missing

**extras**
- Cluebook
- Security Access Matrix
- InvisiClues
- Codewheel
- Map
- Codes

**Comment by TimberlAndRE-de** [comment]
found

- [ ] DOS manual
- [ ] interactive code wheel

added to the github folder

**Comment by exoscoriae** [comment]
added both
