### ISSUE TITLE
Mixed Up Mother Goose

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#537]
**manual**
DOS / WIN manual already included
Atari, Amiga, Apple, FM-Towns is missing

**extras**
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] multi-platform manual for Atari, Amiga, DOS, Macintosh
- [ ] manual addendum for AppleII
- [ ] Reference Card (AppleII)
- [ ] Registration card
- [ ] Poster
- [ ] Rhymes

added to the github folder

**Comment by exoscoriae** [comment]
added
