### ISSUE TITLE
Monkey Island 2 LeChuck's Revenge

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#538]
**manual**
platform independent manual included (for DOS,Mac,Amiga)

**extras**
- Hint book
- Reference Card (IBM)
- VGMap
- interactive code wheel

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Reference card (Amiga)
- [ ] Reference card (Mac)
- [ ] Registration Card

added to the github folder

**Comment by exoscoriae** [comment]
added
