### ISSUE TITLE
Ms Astro Chicken

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#541]
DOS Manual is missing

**Comment by Eulisker** [comment]
This seems to be a demo for Space Quest 3. See [here](https://wiki.scummvm.org/index.php?title=Ms._Astro_Chicken).

It was later released commercially as part of Crazy Nick's Software Picks: Roger Wilco's Spaced Out Game Pack. But i can not find a manual for that.
