### ISSUE TITLE
Once Upon A Time - Little Red Riding Hood

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#550]
DOS and Amiga manual is missing

also this is needed for copy protection (see #142

**Comment by TimberlAndRE-de** [comment]
Eulisker found

- [ ] copy protection codes for the scummVM version

Added to the GitHub folder

**Comment by exoscoriae** [comment]
not seeing the file in the github folder

**Comment by TimberlAndRE-de** [comment]
It's there for me and syno drive says it's synced 🤔 should we asked Boohyaka?

**Comment by exoscoriae** [comment]
added. seems to have arrived now
