### ISSUE TITLE
Operation Stealth

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#553]
**manual**
- DOS & Amiga manual already included

Atari manual is missing

**extras**
- Reference card (IBM, Amiga, Atari) (en,de,it)
- copy protection image

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual for IBM DOS and Amiga

added to the github folder, eXo please set it back to "to do" after processing since the Atari manual is still missing

**Comment by bigjim161** [comment]
Found a multiplatform manual (with a better ref card than the current one in exodos) for Atari, IBM and Amiga in eng-ger-it
Added to the GitHub folder

**Comment by TimberlAndRE-de** [comment]
thx @bigjim161 

- [ ] Atari (+Amiga and IBM) manual as an extra

added to the github folder

**Comment by exoscoriae** [comment]
added
