### ISSUE TITLE
Personal Nightmare

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#564]
**manual**
Atari / Amiga manual included
DOS manual is missing

**extras**
VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Flyer

added to the github folder, eXo please put it back in "to do" for the DOS manual

**Comment by exoscoriae** [comment]
not seeing any flyer in the folder @TimberlAndRE-de

**Comment by TimberlAndRE-de** [comment]
yep, I forgot to copy it over from eXoDOS ;-)
It's there now

**Comment by exoscoriae** [comment]
added
