### ISSUE TITLE
Rosemary

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#608]
WIN manual is missing

**Comment by Eulisker** [comment]
I could not find a manual for this one. The readme is also very uninteresting and only has info about how to install the game. 
I did find 2 interesting documents about the game though. If i understand it correctly it was part of a research project about adventure games and game design in general. You can read about it [here](http://gambit.mit.edu/loadgame/rosemary.php)

I added the research paper and a pdf of the blogpost about the game and its making to the github folder.

**Comment by exoscoriae** [comment]
interesting finds
