### ISSUE TITLE
Secret of Monkey Island, The 

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#611]
**manual**
platform independent manual included (for DOS, Mac, Amiga, Atari)
Sega CD and FM-Towns are missing

**extras**
- Reference Card (IBM)
- Interactive code wheel

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Sega CD manual
- [ ] Reference card (IBM 256 VGA)
- [ ] Reference card (Amiga)
- [ ] Reference card (Atari)
- [ ] Hint Book
- [ ] Hint Book order card
- [ ] Design Notebook
- [ ] Design Notebook scribblings 1
- [ ] Design Notebook scribblings 2

added to the github folder

**Comment by exoscoriae** [comment]
added
