### ISSUE TITLE
Simon the Sorcerer 1

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#617]
**manual**
DOS manual already included
Amiga and Acorn manuals are missing

**extras**
- alternate manual (DOS)
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] reference card (Amiga)
- [ ] reference card (Amiga CD32)

added to the github folder

**Comment by exoscoriae** [comment]
added
