### ISSUE TITLE
Simon the Sorcerer 2

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#618]
**manual**
WIN manual included
DOS, Amiga and Mac are missing

**extras**
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] non-platform manual (de/en)
- [ ] reference card (WIN)
- [ ] registration card UK

eXo, the current manual contains the infos from the non-platform manual and the reference card but is also a digital one from the WIN cd release
so maybe replace it with this non-platform manual to use it for DOS, Amiga, Mac 
and add the reference card for WIN (then all the info is included as with the current manual) and then we need to find reference cards for DOS, Amiga and Mac ...

added to the github folder

**Comment by exoscoriae** [comment]
added
