### ISSUE TITLE
Space Quest 2 - Vohaul's Revenge

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#626]
**manual**
non-platform manual included (for DOS, WIN, Mac, Apple, Amiga, Atari)

**extras**
- IA Game Manual
- Hint Book
- Space Piston Comic
- SQ1-4 Authorized Companion
- SQ1-4 Official Guide

**Comment by TimberlAndRE-de** [comment]
found

- [ ] reference card (Atari)

added to the github folder

**Comment by exoscoriae** [comment]
added
