### ISSUE TITLE
Space Quest 3 - The Pirates of Pestulon

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#627]
**manual**
multi-platform manual already included for Amiga, DOS, Atari
MAC manual is missing

**extras**
- Hint Book
- SQ1-4 Authorized Companion
- SQ1-4 Official Guide
- Glasses
- VGMap

**Comment by TimberlAndRE-de** [comment]
found

- [ ] warranty registration card
- [ ] reference card (Amiga)

added to the github folder

**Comment by exoscoriae** [comment]
added
