### ISSUE TITLE
Trinity

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#652]
**manual**
DOS manual is missing

**extras**
- Cluebook
- InvisiClues
- Crane
- Map
- Sundial

**Comment by TimberlAndRE-de** [comment]
found

- [ ] DOS manual

added to the github folder

and 
- [ ] I found the "Trinity" extras (Cluebook, InvisiClues, Crane, Map, Sundial) in 

- Jinxter
- Myth
- Guild of Thieves, The
- Pawn, The
- Wonderland

extras folders ... 
I can't see why they should be there?
I guess the extras in the folders have to be deleted

**Comment by exoscoriae** [comment]
added manual. removed extras from other games.
