### ISSUE TITLE
Ween The Prophecy

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#662]
**manual**
DOS manual already included
Amiga & Atari manuals are missing

**extras**
- Copy Protection codes
- Hintbook

**Comment by TimberlAndRE-de** [comment]
found

- [ ] european manual (de,en,fr,it) with Amiga & Atari (& DOS) startup instructions

added to the github folder

**Comment by exoscoriae** [comment]
added
