### ISSUE TITLE
Where in Time is Carmen Sandiego

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#663]
it's the 1997 release - it had a ACME Agent Handbook as manual

**Comment by SmilingSpectre** [comment]
https://macintoshgarden.org/sites/macintoshgarden.org/files/manuals/cstime.pdf

**Comment by TimberlAndRE-de** [comment]
thx Spectre

- [ ] manual for Win and Mac found

added to the github folder

**Comment by exoscoriae** [comment]
added
