### ISSUE TITLE
Winnie the Pooh in the Hundred Acre Wood

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#665]
**manual**
non-platform manual already included (with DOS Reference card on last page)

**Comment by TimberlAndRE-de** [comment]
found

- [ ] map
- [ ] C64 manual
- [ ] Apple / C64 teachers guide
- [ ] Apple / C64 worksheets
- [ ] Apple Challenge activity
- [ ] C64 Challenge activity
- [ ] Apple / C64 progress chart

added to the github folder

**Comment by exoscoriae** [comment]
added
