### ISSUE TITLE
Zak McKracken and the Alien Mindbenders

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#671]
**manual**
DOS, Amiga, Atari multi-platform manual inlcuded
C64 manual is missing

**extras**
- The National Inquisitor
- Zap Em II - Security System
- Hintbook

**Comment by TimberlAndRE-de** [comment]
found

- [ ] C64/AppleII/IBM manual as an extra

added to the github folder

**Comment by exoscoriae** [comment]
added
