### ISSUE TITLE
Zork II - The Wizard of Frobozz

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#675]
**manual**
DOS manual is missing

**extras**
- Bozbarland Brochure
- Cluebook
- Grayslopes Brochure
- Invisiclues Map
- Hintbook
- Poster
- Hintbook 2
- Alternate Manual

**Comment by TimberlAndRE-de** [comment]
found

- [ ] DOS manual

added to the github folder

**Comment by exoscoriae** [comment]
added
