### ISSUE TITLE
Trojan Detected in Prince and the Coward

### ISSUE THREAD

**Issue by EarthBoundX5** [exoscoriae/eXoScummVM#685]
Windows Defender is detecting the latest release as containing a Trojan.  Specifically Trojan:Win32/Ymacco.AA31

Found in the following file...
.\eXoScummVM\eXo\eXoScummVM\Prince and the Coward, The (CD Windows).zip->Prince and the Coward, The (CD Windows)/UNINST.EXE

Here is a submission of the file to VirusTotal, given the number of detection and that it appears to phone home, I'd say the detection could be accurate.

https://www.virustotal.com/gui/file/317b1273d9eecd700f41e00e7c60389e742035e9a75edf1ef2f48173d97196ee/detection

**Comment by exoscoriae** [comment]
easy enough to remove that file. it isn't required by scummvm.

either way. scummvm doesn't allow access to the internet or anything on the host computer. so I don't see it as an issue.
