### ISSUE TITLE
Might and Magic IV - Clouds of Xeen (Floppy DOS)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#698]
The game has issues with stable 2.5 ScummVM build, and will only work using the 2.3_18903 svn build

**Comment by exoscoriae** [comment]
is listed as being stable since 2.1.0
what issues made it unstable in 2.5?
I have moved it to 2.6.1 barring any information that would suggest it is still unstable

**Comment by exoscoriae** [comment]
issues have been fixed. using stable 2.6.1 now
