### ISSUE TITLE
Philip Marlowe - Private Eye (CD Windows)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#702]
The game has issues with stable 2.5 ScummVM build, and will only work using the 2.3_18903 svn build

**Comment by exoscoriae** [comment]
using svn 2.7 currently.

**Comment by Python-Exoproject** [comment]
This is an officially supported game so I looked into why it wasnt loading in 2.6.1 and found that the game wont load unless the language flag is set to US. This is possible from the command line and ive set the game up to do so. Now working in official release
