### ISSUE TITLE
Games that have specified sections in scummvm.ini

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#710]
Eye of the Beholder: To allow EOB II to see EOB 1 saves and separate PC98 saves from the others as not cross compatible. Also needs an ini section so that scummvm can add the needed flag that marks the default party as imported

Eye of the Beholder II: To separate FM Towns saves from the others as not cross compatible. Also needs an ini section so that scummvm can add the needed flag that marks the default party as imported

King's Quest VI: To allow both HiRes and LowRes versions

Lands of Lore - The Throne of Chaos: To use smooth_scrolling and get around cross save incompatibility between platform versions

Longest Journey: To use antialiasing

Ultima IV: The internal game options are saved into the scummvm.ini file, but only if the section already exists. Without creating the sections no user settings are saved. Also, the journey onward to continue a previous game uses one of these settings and will not work if U4 is not added specifically to the ini.

Simon the Sorcerer1\Elvira 1&2\Waxworks: To allow usage of game specific option "opl3_mode=true" which fixes some bugs in these games sound when using SB option in DOS versions.

**Comment by exoscoriae** [comment]
escape from monkey island no longer checks files on startup

**Comment by exoscoriae** [comment]
confirmed grim fandango no longer checks files on start-up

**Comment by exoscoriae** [comment]
removed ultima 4. it had no engine settings in the latest stable release

**Comment by Python-Exoproject** [comment]
Replaced Ultima 4 back into the ini. Any settings a user makes in the game from the configure menu are saved to the ini. This only happens if the ultima section has previously been added to the ini. The "Journey Onward" feature also needs the section setup to function.

In general ScummVM looks like it assumes you are using their launcher which adds these sections when you add a game and it seems their testers also tend to use this method as a number of games flat out fail or have issues like this when launching from command line unless you have manually created a section in the ini. A future feature request for ScummVM might be to get ScummVM to create sections in the ini when a game is launched from command line if the game requires it to store settings and it doesnt already exist
