### ISSUE TITLE
Discworld 2 (CD DOS)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoScummVM#714]
Game's not starting.

I think it's because of a missing blank in the `Discworld 2 (CD DOS).bat`:

```
IF EXIST.\util\FULL.SEL SET screen=-f
IF EXIST.\util\WIN.SEL SET screen=-F
IF EXIST.\util\AYES.SEL SET screen=%screen% --aspect-ratio
```

there should be a blank in every line after `IF EXISTS`, for me it works then.

**Comment by exoscoriae** [comment]
fixed. was an issue in multiple launch files.
