### ISSUE TITLE
Broken Sword 1 - The Shadow of the Templar (Multi-Platform)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#744]
Recent release of ScummVM (2.7) has changed the detection routines for this game. Our version of the Mac and Windows releases are not currently detected anymore. As a temporary measure I have set these two versions of the game to use 2.5 which still detects them.

**Comment by exoscoriae** [comment]
Windows issue now detects after moving the root *.clu files to a folder named CLUSTERS

Same thing did *not* work for the mac version.

**Comment by Python-Exoproject** [comment]
Now fixed
