### ISSUE TITLE
Elvira 2 - The Jaws of Cerberus (DOS)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#769]
Seems the codewheel we have is the Amiga one and doesnt work to pass the DOS protection making the game unplayable in eXoScummVM.

Mobygames has the same wheel image under both Amiga and German DOS release.

The only way we will know for sure is if someone has the DOS version to confirm I guess.

If you want to test for yourself its pretty quick to trigger the protection. Start the game, move forward to trigger Elvira speech, turn around and drag the dark rock on the side of the path into your inventory, move to the door of the security office, select the rock in your inventory and then select 'throw' on the right hand side when it shows, click the door, move forward a few times and turn right to face the closet, open the door, backup and drag the key from the guards belt to your inventory, move around to the control panel on the guards desk and click on it to zoom in, drag the key to the keyhole, protection triggers

**Comment by Python-Exoproject** [comment]
[Elvira_2_-_The_Jaws_of_Cerberus_Floppy_DOS.zip](https://github.com/exoscoriae/eXoScummVM/files/14967476/Elvira_2_-_The_Jaws_of_Cerberus_Floppy_DOS.zip)

It looks like the problem was that our copy was either a different version or more likely bad in some way. Eulisker has found a copy that works, so just replace our current scummvm copy with this one. If overwriting instead of replacing also delete `013.vga` as this file doesnt exist in Euliskers copy

**Comment by Eulisker** [comment]
ScummVM does not support sound effects in the DOS Version currently. Maybe put another note in at the beginning?

![image](https://github.com/exoscoriae/eXoScummVM/assets/81642149/263b5684-0db9-4cec-8c81-1e253e199c76)
![image](https://github.com/exoscoriae/eXoScummVM/assets/81642149/519077c6-2a91-494f-a4ba-b0c51c6fde40)

**Comment by exoscoriae** [comment]
all of the above has been done, including the modified note.
