### ISSUE TITLE
Leisure Suit Larry 5 - Passionate Patty Does a Little Undercover Work (Macintosh)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoScummVM#88]
When you get past the intro and try to start the actual game the ScummVM console appears saying "ERROR: Unititialized read for temp 1 from method ::export 0 (room 155, script 175, localcall ffffffff)!

The ScummVM console gives a couple of warnings that may be related as well.

According to https://forums.scummvm.org/viewtopic.php?t=14293 its a scipt bug in ScummVM that may have been forgotten about by now.

As it kills the game I am rem'ing out the Mac option for now

**Comment by exoscoriae** [comment]
unable to verify. works good in 2.2. for me.

**Comment by Python-Exoproject** [comment]
Confirmed. 2.2 stable release works ok, the svn release we are using causes the above issue. Switched game to use stable release and re added Mac option
